import React,{useState}from'react';import{GoogleMap}from'../components/UI.jsx';
export default function AdminPanel({state,setState,setRole}){const[tab,setTab]=useState('dash');const[mobileMenu,setMobileMenu]=useState(false);const[adsMode,setAdsMode]=useState('list');const tabs=[['dash','Dashboard'],['urgent','Pilne zgłoszenia'],['rides','Przejazdy'],['map','Mapa live'],['patients','Pacjenci'],['drivers','Kierowcy'],['vehicles','Pojazdy'],['ads','Reklamy'],['payments','Płatności'],['reports','Raporty'],['notify','Powiadomienia'],['users','Użytkownicy'],['settings','Ustawienia']];const Menu=<div className="menu">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMobileMenu(false)}}>{label}</button>)}</div>;return <div className="adminLayout"><div className="adminMobileMenu"><b>OnkoTaxi Admin</b><div style={{display:'flex',gap:8}}><button className="small gray" onClick={()=>setRole('patient')}>Pacjent</button><button className="small gray" onClick={()=>setRole('driver')}>Kierowca</button><button className="small" onClick={()=>setMobileMenu(!mobileMenu)}>Menu</button></div></div>{mobileMenu&&<div className="card" style={{margin:16}}>{Menu}</div>}<aside className="side"><div className="logo">Onko<span>Taxi</span></div><div className="tag">ADMIN PANEL</div>{Menu}</aside><main className="main">
{tab==='dash'&&<><Header title="Dashboard — przegląd sytuacji" sub="Najważniejsze informacje w czasie rzeczywistym."/><div className="kpis"><Kpi label="Łączna liczba przejazdów" value="128"/><Kpi label="Przejazdy zaplanowane" value="24"/><Kpi label="Przejazdy w trakcie" value="18"/><Kpi label="Zgłoszenia pilne" value="5" red/></div><div className="dash"><div className="card"><h2>Aktywne przejazdy na mapie</h2><GoogleMap height={430}/></div><div className="card"><h2>Ostatnie zgłoszenia</h2><Table rows={[["10:15","Mielec → Rzeszów","Nowe"],["09:45","Dębica → Rzeszów","Przypisane"]]}/></div></div></>}
{tab==='urgent'&&<><Header title="Pilne zgłoszenia" sub="Lista wymagająca natychmiastowej reakcji."/><DataTable headers={["Priorytet","Pacjent","Lokalizacja","Cel","Czas","Akcja"]} rows={[["Wysoki","Jan Kowalski","Rzeszów","Centrum Onkologii","2 min","Przypisz kierowcę"],["Wysoki","Anna Nowak","Dębica","Szpital","3 min","Przypisz"]]}/></>}
{tab==='rides'&&<><Header title="Zarządzanie przejazdami" sub="Lista przejazdów i zarządzanie statusami." action="+ Nowy przejazd"/><DataTable headers={["ID","Data i godzina","Pacjent","Trasa","Typ","Status","Kierowca","Pojazd"]} rows={state.rides.map(r=>[r.id,`${r.date} ${r.time}`,r.patient,`${r.pickup} → ${r.destination}`,r.type,r.status,r.driver,r.vehicle])}/></>}
{tab==='map'&&<><Header title="Mapa live — pojazdy i przejazdy" sub="Podgląd wszystkich kierowców i zgłoszeń."/><div className="dash"><div className="card"><GoogleMap height={570}/></div><div className="card"><h2>Aktywne przejazdy</h2>{state.rides.map(r=><p key={r.id}><b>{r.patient}</b><br/>{r.vehicle}<br/>{r.status}</p>)}</div></div></>}
{tab==='patients'&&<><Header title="Zarządzanie pacjentami" sub="Baza pacjentów i historia przejazdów." action="+ Dodaj pacjenta"/><div className="dash"><div className="card"><h2>Profil pacjenta</h2><div className="driverCard"><div className="avatar">JK</div><div><b>Jan Kowalski</b><br/>+48 600 123 456<br/>jan.kowalski@email.com</div></div><p>Opiekun: Anna Kowalska · +48 600 654 321</p></div><div className="card"><h2>Historia przejazdów</h2><DataTable headers={["Data","Trasa","Kierowca","Status"]} rows={state.rides.map(r=>[r.date,`${r.pickup} → ${r.destination}`,r.driver,r.status])}/></div></div></>}
{tab==='drivers'&&<><Header title="Zarządzanie kierowcami" sub="Lista kierowców i dostępność." action="+ Dodaj kierowcę"/><div className="kpis"><Kpi label="Łącznie" value="40"/><Kpi label="Online" value="32"/><Kpi label="Offline" value="8" red/><Kpi label="Niedostępni" value="2"/></div><DataTable headers={["Kierowca","Pojazd","Status","Ocena"]} rows={state.drivers.map(d=>[d.name,d.vehicle,d.status,d.rating])}/></>}
{tab==='vehicles'&&<><Header title="Pojazdy" sub="Flota i status techniczny." action="+ Dodaj pojazd"/><DataTable headers={["Pojazd","Kierowca","Typ","Rok","Status","Przegląd"]} rows={[["RZ 1234A Toyota RAV4","Jan Nowak","SUV","2020","Dostępny","25.07.2024"],["RZ 5678 Toyota Corolla","Anna Nowak","Sedan","2019","W trasie","12.06.2024"]]}/></>}
{tab==='ads'&&<Ads state={state} setState={setState} mode={adsMode} setMode={setAdsMode}/>} 
{tab==='payments'&&<><Header title="Płatności" sub="Rozliczenia i zwroty."/><div className="kpis"><Kpi label="Przychód" value="45 231 zł"/><Kpi label="Płatności" value="41 231 zł"/><Kpi label="Oczekujące" value="2 450 zł"/><Kpi label="Zwroty" value="1 550 zł" red/></div><DataTable headers={["ID","Data","Pacjent","Kwota","Metoda","Status"]} rows={[["PAY/0356","31.05","Jan Kowalski","95 zł","Karta","Zakończone"]]}/></>}
{tab==='reports'&&<><Header title="Raporty i analityka" action="Eksportuj raport"/><div className="kpis"><Kpi label="Liczba przejazdów" value="428"/><Kpi label="Planowane" value="312"/><Kpi label="Pilne" value="116"/><Kpi label="Śr. czas" value="24 min"/></div><div className="dash"><div className="card"><h2>Liczba przejazdów w czasie</h2><div className="chart"><div className="bar" style={{left:45,height:60}}/><div className="bar" style={{left:103,height:90}}/><div className="bar" style={{left:161,height:76}}/><div className="bar" style={{left:219,height:130}}/></div></div><div className="card"><h2>Analityka</h2><div className="adPreview" style={{backgroundImage:"url('https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=1600&auto=format&fit=crop')"}}><h2>OnkoTaxi</h2></div></div></div></>}
{tab==='notify'&&<><Header title="Powiadomienia systemowe"/><Table rows={[["⚠","Zgłoszenie pilne #23061","Pilne"],["ℹ","Przejazd zakończony","Info"]]}/></>}
{tab==='users'&&<><Header title="Zarządzanie użytkownikami" action="+ Dodaj użytkownika"/><DataTable headers={["Imię i nazwisko","Email","Rola","Status","Data dodania"]} rows={[["Jan Kowalski","jan.kowalski@onkotaxi.pl","Administrator","Aktywny","01.05"],["Anna Nowak","anna.nowak@onkotaxi.pl","Operator","Aktywny","02.05"]]}/></>}
{tab==='settings'&&<><Header title="Ustawienia systemu" action="Zapisz zmiany"/><div className="settings"><div className="card"><h2>Ustawienia ogólne</h2><div className="field"><div><label>Nazwa aplikacji</label><input defaultValue="OnkoTaxi"/></div></div><div className="field"><div><label>Email kontaktowy</label><input defaultValue="kontakt@onkotaxi.pl"/></div></div></div><div className="card"><h2>Ustawienia przejazdów</h2><div className="field"><div><label>Maksymalny czas oczekiwania</label><input defaultValue="15 min"/></div></div><div className="field"><div><label>Auto przypisywanie kierowców</label><input defaultValue="Włączone"/></div></div></div></div></>}
</main></div>}
function Header({title,sub,action}){return <div className="toolbar"><div><h1>{title}</h1>{sub&&<p className="muted">{sub}</p>}</div>{action&&<button className="small">{action}</button>}</div>}
function Kpi({label,value,red}){return <div className="kpi"><small>{label}</small><strong style={red?{color:'var(--red)'}:{}}>{value}</strong></div>}
function Table({rows}){return <table className="table"><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>}
function DataTable({headers,rows}){return <table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>}
function Ads({state,setState,mode,setMode}){function saveAd(){setState({...state,ads:[{id:'AD'+Date.now(),name:'Nowa reklama',placement:'Ekran główny',impressions:0,clicks:0,status:'Aktywna'},...state.ads]});setMode('list')}if(mode==='form')return <><Header title="Dodaj reklamę" sub="Tworzenie nowej kampanii reklamowej."/><div className="dash"><div className="card"><h2>Dane reklamy</h2><div className="field"><div><label>Nazwa kampanii</label><input defaultValue="Nowa kampania"/></div></div><div className="field"><div><label>Klient / marka</label><input defaultValue="Partner medyczny"/></div></div><div className="field"><div><label>Lokalizacja</label><select defaultValue="Ekran główny"><option>Ekran główny</option><option>Planowanie przejazdu</option><option>Tracking</option><option>Kierowca dashboard</option></select></div></div><button className="btn" onClick={saveAd}>Zapisz reklamę</button> <button className="btn light" onClick={()=>setMode('list')}>Anuluj</button></div><div className="card"><h2>Podgląd</h2><div className="adPreview" style={{backgroundImage:"url('https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1600&auto=format&fit=crop')"}}><small>REKLAMA</small><h2>Nie czekaj.<br/>Jedź bezpiecznie.</h2><p>Toyota RAV4 Hybrid</p></div></div></div></>;if(mode==='detail')return <><Header title="Szczegóły kampanii" sub="Wyniki skuteczności i ustawienia."/><div className="dash"><div className="card"><div className="adPreview" style={{backgroundImage:"url('https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1600&auto=format&fit=crop')"}}><small>REKLAMA</small><h2>Toyota RAV4 Hybrid</h2><p>Bezpieczny przejazd na leczenie</p></div><p><b>Status:</b> Aktywna<br/><b>Budżet:</b> 2000 zł<br/><b>Okres:</b> 01.05–31.05</p><button className="btn" onClick={()=>setMode('list')}>Powrót</button></div><div className="card"><h2>Wyniki</h2><div className="chart"><div className="bar" style={{left:45,height:70}}/><div className="bar" style={{left:103,height:90}}/><div className="bar" style={{left:161,height:110}}/><div className="bar" style={{left:219,height:130}}/></div></div></div></>;return <><Header title="Zarządzanie reklamami" sub="Twórz, edytuj i analizuj kampanie reklamowe."/><button className="small" onClick={()=>setMode('form')} style={{marginBottom:16}}>+ Nowa reklama</button><div className="kpis"><Kpi label="Kampanie" value={state.ads.length}/><Kpi label="Wyświetlenia" value="45 378"/><Kpi label="Kliknięcia" value="1 245"/><Kpi label="CTR" value="2,75%"/></div><table className="table"><thead><tr><th>Nazwa</th><th>Lokalizacja</th><th>Wyświetlenia</th><th>Kliknięcia</th><th>Status</th><th>Akcje</th></tr></thead><tbody>{state.ads.map(ad=><tr key={ad.id}><td>{ad.name}</td><td>{ad.placement}</td><td>{ad.impressions}</td><td>{ad.clicks}</td><td><span className="badge">{ad.status}</span></td><td><button className="small gray" onClick={()=>setMode('detail')}>Szczegóły</button></td></tr>)}</tbody></table></>}
