import React,{useState}from'react';import{PhoneShell,BottomNav,GoogleMap}from'../components/UI.jsx';
export default function DriverApp({state,setState,setRole}){const[screen,setScreen]=useState('login');const ride=state.rides[0];function updateRide(status){setState({...state,rides:state.rides.map((r,i)=>i===0?{...r,status}:r)})}function triggerSOS(){setState({...state,sos:{driver:'Piotr Nowak',rideId:ride?.id||'OT-001',location:'ul. Leśna 10, Mielec',time:new Date().toLocaleTimeString()}});setScreen('sos')}const bottom=<BottomNav active={screen} setScreen={setScreen} items={[{id:'dash',screen:'dash',label:'Start',icon:'home'},{id:'orders',screen:'orders',label:'Zlecenia',icon:'car'},{id:'history',screen:'history',label:'Historia',icon:'rides'},{id:'profile',screen:'profile',label:'Profil',icon:'profile'}]}/>;const roleMenu=<div className="card"><b>Wybór roli</b><div style={{display:'grid',gap:8,marginTop:10}}><button className="btn light" onClick={()=>setRole('patient')}>Pacjent</button><button className="btn light" onClick={()=>setRole('driver')}>Kierowca</button><button className="btn light" onClick={()=>setRole('admin')}>Admin</button></div></div>;return <PhoneShell roleMenu={roleMenu} bottomNav={bottom} drawerItems={[{label:'Start',onClick:()=>setScreen('dash')},{label:'Zlecenia',onClick:()=>setScreen('orders')},{label:'Historia',onClick:()=>setScreen('history')},{label:'Profil',onClick:()=>setScreen('profile')}]}>
{['details','nav','arrived','picked','trip'].includes(screen)&&<button className="sos" onClick={triggerSOS}>SOS</button>}
{screen==='login'&&<><h2 className="screenTitle" style={{textAlign:'center'}}>Logowanie kierowcy</h2><div className="success" style={{fontSize:44}}>🚕</div><div className="field"><div><label>E-mail</label><input defaultValue="piotr.nowak@onkotaxi.pl"/></div></div><div className="field"><div><label>Hasło</label><input type="password" defaultValue="haslo123"/></div></div><button className="btn full" onClick={()=>setScreen('dash')}>Zaloguj się</button></>}
{screen==='dash'&&<><h2 className="screenTitle">Witaj, Piotr!</h2><div className="card" style={{background:'#eaf8f6'}}><b>Twój status</b><h2 style={{color:'var(--teal)',margin:'8px 0'}}>ONLINE</h2><p className="muted">Jesteś gotowy na zlecenia</p></div><div className="trackingInfo"><div className="infoBox"><small>Zlecenia</small><b>{state.rides.length}</b></div><div className="infoBox"><small>Przejechane</small><b>210 km</b></div></div><div className="card"><span className="badge red">{ride?.type||'NOWE'}</span><h3>Najbliższe zlecenie</h3><p>{ride?.patient}<br/>{ride?.pickup} → {ride?.destination}<br/>Odbiór: {ride?.time}</p><button className="btn full" onClick={()=>setScreen('new')}>Zobacz szczegóły</button></div></>}
{screen==='orders'&&<><h2 className="screenTitle">Zlecenia</h2>{state.rides.map(r=><div className="listTile" key={r.id} onClick={()=>setScreen('new')}><div><b>{r.patient}</b><br/><small>{r.pickup} → {r.destination}</small></div><span>›</span></div>)}</>}
{screen==='new'&&<><h2 className="screenTitle">Nowe zlecenie</h2><div className="card"><span className="badge red">{ride?.type}</span><p><b>Pacjent</b><br/>{ride?.patient}</p><p><b>Odbiór</b><br/>{ride?.pickup}</p><p><b>Cel</b><br/>{ride?.destination}</p><p><b>Godzina odbioru</b><br/>{ride?.time}</p></div><button className="btn full" onClick={()=>{updateRide('Kierowca przyjął zlecenie');setScreen('details')}}>Przyjmij zlecenie</button><br/><br/><button className="btn secondary full" onClick={()=>setScreen('dash')}>Odrzuć zlecenie</button></>}
{screen==='details'&&<><h2 className="screenTitle">Szczegóły zlecenia</h2><div className="card"><b>{ride?.patient}</b><p>Opiekun: {ride?.caregiver}<br/>Tel.: {ride?.caregiverPhone}</p><button className="btn full">Zadzwoń</button></div><div className="card"><b>Odbiór</b><p>{ride?.pickup}</p><b>Cel podróży</b><p>{ride?.destination}</p>{ride?.needsHelp&&<><b>Pomoc</b><p>{ride.helpNote||'Pacjent potrzebuje pomocy przy wsiadaniu.'}</p></>}</div><button className="btn full" onClick={()=>{updateRide('Kierowca jedzie do pacjenta');setScreen('nav')}}>Nawiguj do pacjenta</button></>}
{screen==='nav'&&<><h2 className="screenTitle">Do pacjenta</h2><div className="card"><b>{ride?.pickup}</b><br/><span className="muted">ETA: 6 min · odległość 2.4 km</span></div><GoogleMap height={230}/><br/><button className="btn full" onClick={()=>{updateRide('Kierowca dotarł na miejsce');setScreen('arrived')}}>Dotarłem na miejsce</button></>}
{screen==='arrived'&&<><div className="success">✓</div><h2 className="screenTitle" style={{textAlign:'center'}}>Jesteś na miejscu</h2><p className="lead" style={{textAlign:'center'}}>{ride?.pickup}</p><div className="card"><b>Pacjent</b><p>{ride?.patient}</p><b>Opiekun</b><p>{ride?.caregiver}</p></div><button className="btn full" onClick={()=>{updateRide('Pacjent odebrany');setScreen('picked')}}>Pacjent odebrany</button></>}
{screen==='picked'&&<><div className="success">✓</div><h2 className="screenTitle" style={{textAlign:'center'}}>Pacjent odebrany</h2><div className="card"><b>Cel podróży</b><p>{ride?.destination}</p><b>Szacowany czas</b><p>45 min · 48 km</p></div><button className="btn full" onClick={()=>{updateRide('W trakcie przejazdu');setScreen('trip')}}>Rozpocznij przejazd</button></>}
{screen==='trip'&&<><h2 className="screenTitle">W trakcie przejazdu</h2><div className="trackingInfo"><div className="infoBox"><small>ETA</small><b>14:45</b></div><div className="infoBox"><small>Pozostało</small><b>32 km</b></div></div><GoogleMap height={230}/><br/><button className="btn secondary">Zadzwoń do centrali</button> <button className="btn secondary">Zgłoś opóźnienie</button><br/><br/><button className="btn full" onClick={()=>{updateRide('Przejazd zakończony');setScreen('finish')}}>Zakończ przejazd</button></>}
{screen==='sos'&&<><div style={{background:'linear-gradient(180deg,#ff1f35,#e31325)',color:'white',borderRadius:18,padding:24,textAlign:'center',marginBottom:14}}><h1>⚠ SOS</h1><p>Czy chcesz zadzwonić pod numer alarmowy 112?</p><a className="btn full" href="tel:112" style={{background:'white',color:'var(--red)',display:'block',textDecoration:'none'}}>Zadzwoń pod 112</a></div><div className="card"><b>Informacje o przejeździe</b><p>{ride?.id}<br/>Pacjent: {ride?.patient}<br/>Kierowca: Piotr Nowak</p></div><button className="btn secondary full" onClick={()=>setScreen('trip')}>Anuluj</button></>}
{screen==='finish'&&<><div className="success">✓</div><h2 className="screenTitle" style={{textAlign:'center'}}>Przejazd zakończony</h2><div className="card"><b>Podsumowanie</b><p>Pacjent: {ride?.patient}<br/>Trasa: Mielec → Rzeszów<br/>Dystans: 48 km<br/>Czas: 52 min</p></div><div className="field"><div><label>Notatka</label><textarea placeholder="Dodaj notatkę..."/></div></div><button className="btn full" onClick={()=>setScreen('dash')}>Zakończ i wróć do dashboardu</button></>}
{screen==='history'&&<><h2 className="screenTitle">Historia przejazdów</h2>{state.rides.map(r=><div className="listTile" key={r.id}><div><b>{r.time}</b><br/><small>{r.patient} · {r.status}</small></div><span className="badge">Zakończony</span></div>)}</>}
{screen==='profile'&&<><h2 className="screenTitle">Profil kierowcy</h2><div className="driverCard"><div className="avatar">PN</div><div><b>Piotr Nowak</b><br/><span style={{color:'#ff9800'}}>★</span> 4.9<br/><small>Ocena klientów</small></div></div><br/><div className="card"><b>Dane kierowcy</b><p>+48 600 123 456<br/>piotr.nowak@onkotaxi.pl<br/>Status: zweryfikowany</p></div></>}
</PhoneShell>}
