import React,{useState}from'react';import{PhoneShell,BottomNav,Ad,GoogleMap,Field}from'../components/UI.jsx';
function todayPlus(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
export default function PatientApp({state,setState,setRole}){const[screen,setScreen]=useState('landing');const[form,setForm]=useState({date:todayPlus(7),time:'10:00',needsHelp:'Nie',helpNote:'',companion:'Tak'});const bottom=<BottomNav active={screen} setScreen={setScreen} items={[{id:'home',screen:'home',label:'Start',icon:'home'},{id:'history',screen:'history',label:'Przejazdy',icon:'rides'},{id:'notify',screen:'notify',label:'Powiadomienia',icon:'alerts'},{id:'profile',screen:'profile',label:'Profil',icon:'profile'}]}/>;const roleMenu=<div className="card"><b>Wybór roli</b><div style={{display:'grid',gap:8,marginTop:10}}><button className="btn light" onClick={()=>setRole('patient')}>Pacjent</button><button className="btn light" onClick={()=>setRole('driver')}>Kierowca</button><button className="btn light" onClick={()=>setRole('admin')}>Admin</button></div></div>;function createRide(type='PLANOWANY'){const ride={id:'OT-'+Date.now().toString().slice(-5),patient:'Jan Kowalski',caregiver:'Anna Kowalska',caregiverPhone:'+48 600 654 321',pickup:'ul. Leśna 10, Mielec',destination:'Centrum Onkologii, Rzeszów',date:form.date,time:form.time,type,status:type==='PILNY'?'Pilny — oczekuje na kierowcę':'Zaplanowany',needsHelp:form.needsHelp==='Tak',helpNote:form.helpNote,driver:'Jan Nowak',vehicle:'Toyota RAV4 · RZ 1234A'};setState({...state,rides:[ride,...state.rides]});setScreen('tracking')}return <PhoneShell roleMenu={roleMenu} bottomNav={bottom} drawerItems={[{label:'Start',onClick:()=>setScreen('home')},{label:'Moje przejazdy',onClick:()=>setScreen('history')},{label:'Powiadomienia',onClick:()=>setScreen('notify')},{label:'Profil i dokumenty',onClick:()=>setScreen('profile')}]}>
{screen==='landing'&&<><Ad type="car"/><h2 className="screenTitle" style={{textAlign:'center'}}>Razem w drodze<br/>do zdrowia</h2><p className="lead" style={{textAlign:'center'}}>Bezpłatny transport dla pacjentów onkologicznych i ich opiekunów.</p><button className="btn full" onClick={()=>setScreen('reg1')}>Zarejestruj się</button><br/><br/><button className="btn secondary full" onClick={()=>setScreen('login')}>Zaloguj się</button></>}
{screen==='login'&&<><h2 className="screenTitle">Logowanie</h2><p className="lead">Dostęp tylko dla zweryfikowanych pacjentów.</p><Field label="E-mail" icon="✉"><input defaultValue="jan.kowalski@email.com"/></Field><Field label="Hasło" icon="🔒"><input type="password" defaultValue="haslo123"/></Field><button className="btn full" onClick={()=>setScreen('home')}>Zaloguj się</button><Ad type="med"/></>}
{screen==='reg1'&&<><h2 className="screenTitle">Dane pacjenta</h2><div className="progress"><b style={{width:'25%'}}/></div><Field label="Imię i nazwisko" icon="👤"><input defaultValue="Jan Kowalski"/></Field><Field label="Data urodzenia" icon="📅"><input defaultValue="12.05.1965"/></Field><Field label="Adres zamieszkania" icon="📍"><input defaultValue="ul. Leśna 10, 39-300 Mielec"/></Field><Field label="Telefon" icon="☎"><input defaultValue="+48 600 123 456"/></Field><Field label="E-mail" icon="✉"><input defaultValue="jan.kowalski@email.com"/></Field><button className="btn full" onClick={()=>setScreen('reg2')}>Dalej</button><Ad type="car"/></>}
{screen==='reg2'&&<><h2 className="screenTitle">Opiekun</h2><div className="progress"><b style={{width:'50%'}}/></div><p className="lead">Osoba do kontaktu w nagłych sytuacjach.</p><Field label="Imię i nazwisko opiekuna" icon="👤"><input defaultValue="Anna Kowalska"/></Field><Field label="Telefon opiekuna" icon="☎"><input defaultValue="+48 600 654 321"/></Field><button className="btn full" onClick={()=>setScreen('reg3')}>Dalej</button></>}
{screen==='reg3'&&<><h2 className="screenTitle">Dokumenty</h2><div className="progress"><b style={{width:'75%'}}/></div><p className="lead">Dołącz dokumenty potwierdzające leczenie.</p><div className="card" style={{textAlign:'center',borderStyle:'dashed',padding:22}}><b>Dodaj dokumenty</b><p className="muted">PDF, zdjęcia, wyniki badań</p><button className="btn secondary">Wybierz plik</button></div><div className="listTile"><div><span className="badge red">PDF</span> Historia choroby.pdf<br/><small className="muted">1.2 MB</small></div><span>×</span></div><div className="listTile"><div><span className="badge">JPG</span> Wyniki badań.jpg<br/><small className="muted">2.5 MB</small></div><span>×</span></div><button className="btn full" onClick={()=>setScreen('reg4')}>Dalej</button><Ad type="pharma"/></>}
{screen==='reg4'&&<><h2 className="screenTitle">Podsumowanie</h2><div className="progress"><b style={{width:'100%'}}/></div><div className="card"><b>Dane pacjenta</b><p>Jan Kowalski, 12.05.1965<br/>ul. Leśna 10, Mielec<br/>+48 600 123 456</p><b>Opiekun</b><p>Anna Kowalska · +48 600 654 321</p><b>Dokumenty</b><p>2 pliki dodane</p></div><button className="btn full" onClick={()=>setScreen('verify')}>Zakończ rejestrację</button></>}
{screen==='verify'&&<><div className="success">✉</div><h2 className="screenTitle" style={{textAlign:'center'}}>Sprawdź swoją skrzynkę e-mail</h2><p className="lead" style={{textAlign:'center'}}>Wysłaliśmy link aktywacyjny na jan.kowalski@email.com</p><button className="btn full" onClick={()=>setScreen('home')}>Aktywuj konto</button><Ad type="car"/></>}
{screen==='home'&&<><div className="homeHero"><h2>Witaj, Jan!</h2><p className="lead">Jak możemy Ci pomóc?</p></div><div className="service green" onClick={()=>setScreen('plan1')}><div className="left"><div className="bubble">▣</div><div><b>PLANUJ PODRÓŻ</b><small>Transport planowany<br/>min. 7 dni wcześniej</small></div></div><span className="arrow">›</span></div><div className="service red" onClick={()=>createRide('PILNY')}><div className="left"><div className="bubble">!</div><div><b>TRANSPORT PILNY</b><small>Szybki transport<br/>w nagłych przypadkach</small></div></div><span className="arrow">›</span></div><div className="listTile" onClick={()=>setScreen('history')}><b>Moje przejazdy</b><span>›</span></div><div className="listTile" onClick={()=>setScreen('profile')}><b>Kontakt / pomoc</b><span>›</span></div><Ad type="car"/></>}
{screen==='plan1'&&<><h2 className="screenTitle">Skąd i dokąd?</h2><div className="progress"><b style={{width:'20%'}}/></div><Field label="Skąd" icon="📍"><input defaultValue="ul. Leśna 10, 39-300 Mielec"/></Field><Field label="Dokąd" icon="🏥"><input defaultValue="Centrum Onkologii, Rzeszów"/></Field><div className="placeGrid"><div className="place">Szpital</div><div className="place">Dom</div><div className="place">Inne miejsce</div></div><button className="btn full" onClick={()=>setScreen('plan2')}>Dalej</button><Ad type="car"/></>}
{screen==='plan2'&&<><h2 className="screenTitle">Data i godzina odbioru</h2><div className="progress"><b style={{width:'40%'}}/></div><p className="lead">Rezerwacja z minimum 7-dniowym wyprzedzeniem.</p><Field label="Data" icon="📅"><input type="date" min={todayPlus(7)} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Godzina odbioru z miejsca wskazanego" icon="🕙"><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></Field><button className="btn full" onClick={()=>setScreen('plan3')}>Dalej</button></>}
{screen==='plan3'&&<><h2 className="screenTitle">Osoba towarzysząca</h2><div className="progress"><b style={{width:'60%'}}/></div><Field label="Imię i nazwisko" icon="👤"><input defaultValue="Anna Kowalska"/></Field><Field label="Telefon" icon="☎"><input defaultValue="+48 600 654 321"/></Field><Field label="Czy jedzie z pacjentem?" icon="✓"><select value={form.companion} onChange={e=>setForm({...form,companion:e.target.value})}><option>Tak</option><option>Nie, tylko kontakt</option></select></Field><button className="btn full" onClick={()=>setScreen('plan4')}>Dalej</button></>}
{screen==='plan4'&&<><h2 className="screenTitle">Szczegóły przejazdu</h2><div className="progress"><b style={{width:'80%'}}/></div><Field label="Czy pacjent potrzebuje pomocy przy wsiadaniu?" icon="♿"><select value={form.needsHelp} onChange={e=>setForm({...form,needsHelp:e.target.value})}><option>Nie</option><option>Tak</option></select></Field>{form.needsHelp==='Tak'&&<Field label="Opisz potrzebną pomoc" icon="✎"><textarea value={form.helpNote} onChange={e=>setForm({...form,helpNote:e.target.value})} placeholder="Np. pomoc przy wejściu do auta, wózek, asekuracja..."/></Field>}<div className="driverCard"><div className="avatar">JN</div><div><b>Jan Nowak</b><br/><span style={{color:'#ff9800'}}>★</span> 4.9 (128)<br/><small className="muted">Toyota RAV4 · RZ 1234A</small></div><div style={{marginLeft:'auto',fontSize:30}}>🚘</div></div><br/><button className="btn full" onClick={()=>setScreen('plan5')}>Dalej</button></>}
{screen==='plan5'&&<><h2 className="screenTitle">Podsumowanie</h2><div className="progress"><b style={{width:'100%'}}/></div><div className="card"><b>Planowany przejazd</b><p>{form.date}, {form.time}<br/>ul. Leśna 10, Mielec<br/>Centrum Onkologii, Rzeszów</p><b>Kierowca</b><p>Jan Nowak · Toyota RAV4</p><b>Opiekun</b><p>Anna Kowalska · +48 600 654 321</p>{form.needsHelp==='Tak'&&<><b>Pomoc przy wsiadaniu</b><p>{form.helpNote||'Wymagana pomoc przy wsiadaniu.'}</p></>}</div><button className="btn full" onClick={()=>createRide('PLANOWANY')}>Potwierdź przejazd</button></>}
{screen==='tracking'&&<><h2 className="screenTitle">Twój przejazd</h2><p className="lead">{state.rides[0]?.status||'Kierowca w drodze'}</p><GoogleMap height={230}/><div className="trackingInfo"><div className="infoBox"><small>Czas dojazdu</small><b>12 min</b></div><div className="infoBox"><small>Dystans</small><b>15,2 km</b></div></div><div className="driverCard"><div className="avatar">JN</div><div><b>Jan Nowak</b><br/><span style={{color:'#ff9800'}}>★</span> 4.9 (128)<br/><small className="muted">Toyota RAV4 · RZ 1234A</small></div></div><br/><button className="btn secondary full">Kontakt z kierowcą</button><Ad type="car"/></>}
{screen==='history'&&<><h2 className="screenTitle">Moje przejazdy</h2>{state.rides.map(r=><div className="listTile" key={r.id}><div><b>{r.date||'23.05.2024'}, {r.time}</b><br/><small>{r.pickup} → {r.destination}</small></div><span className="badge">{r.status}</span></div>)}</>}
{screen==='notify'&&<><h2 className="screenTitle">Powiadomienia</h2><div className="listTile"><div><b>Kierowca przyjął przejazd</b><br/><small>Jan Nowak przyjął Twój przejazd.</small></div></div></>}
{screen==='profile'&&<><h2 className="screenTitle">Profil</h2><div className="driverCard"><div className="avatar">JK</div><div><b>Jan Kowalski</b><br/><small>jan.kowalski@email.com</small></div></div><br/><div className="card"><b>Dokumenty</b><p>Historia choroby.pdf<br/>Wyniki badań.jpg</p></div></>}
</PhoneShell>}
